name: Python Script Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-script:
    name: Test BioPython Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install biopython

      - name: Run script
        run: |
          python fetch_sequences.py nucleotide "Escherichia coli"
        env:
          NCBI_EMAIL: rendrickcarreira@gmail.com