name: Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    name: PEP8
    runs-on: ubuntu-latest
    container: rendrick27/snakemake:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 .

  Test:
    name: Test Script
    runs-on: ubuntu-latest
    container: rendrick27/snakemake:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install biopython

      - name: Run script
        run: |
          python fetch_sequences.py nucleotide "LC020659"
        env:
          NCBI_EMAIL: rendrickcarreira@gmail.com

